apiVersion: v1
kind: Service
metadata:
  name: booking
  labels:
    app: booking
spec:
  type: NodePort
  selector:
    app: booking
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32502  # Ensure this is within the valid range for NodePort


