apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
      - name: hotels
        image: mostafa321/hotels:dev
        ports:
        - containerPort: 8080

