apiVersion: v1
kind: Service
metadata:
  name: hotels
  labels:
    app: hotels
spec:
  type: NodePort
  selector:
    app: hotels
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32504  # Ensure this is within the valid range for NodePort


